package runner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewPostGroupsGroupNameJobsIDErrorParams creates a new PostGroupsGroupNameJobsIDErrorParams object
// with the default values initialized.
func NewPostGroupsGroupNameJobsIDErrorParams() *PostGroupsGroupNameJobsIDErrorParams {
	var ()
	return &PostGroupsGroupNameJobsIDErrorParams{}
}

/*PostGroupsGroupNameJobsIDErrorParams contains all the parameters to send to the API endpoint
for the post groups group name jobs ID error operation typically these are written to a http.Request
*/
type PostGroupsGroupNameJobsIDErrorParams struct {

	/*GroupName
	  Name of group for this set of jobs.

	*/
	GroupName string
	/*ID
	  Job id

	*/
	ID string
	/*Reason
	  Reason for job failure.

	*/
	Reason string
}

// WithGroupName adds the groupName to the post groups group name jobs ID error params
func (o *PostGroupsGroupNameJobsIDErrorParams) WithGroupName(groupName string) *PostGroupsGroupNameJobsIDErrorParams {
	o.GroupName = groupName
	return o
}

// WithID adds the id to the post groups group name jobs ID error params
func (o *PostGroupsGroupNameJobsIDErrorParams) WithID(id string) *PostGroupsGroupNameJobsIDErrorParams {
	o.ID = id
	return o
}

// WithReason adds the reason to the post groups group name jobs ID error params
func (o *PostGroupsGroupNameJobsIDErrorParams) WithReason(reason string) *PostGroupsGroupNameJobsIDErrorParams {
	o.Reason = reason
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostGroupsGroupNameJobsIDErrorParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param group_name
	if err := r.SetPathParam("group_name", o.GroupName); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// form param reason
	frReason := o.Reason
	fReason := frReason
	if fReason != "" {
		if err := r.SetFormParam("reason", fReason); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
