package core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetJobIDParams creates a new GetJobIDParams object
// with the default values initialized.
func NewGetJobIDParams() *GetJobIDParams {
	var ()
	return &GetJobIDParams{}
}

/*GetJobIDParams contains all the parameters to send to the API endpoint
for the get job ID operation typically these are written to a http.Request
*/
type GetJobIDParams struct {

	/*ID
	  Job id

	*/
	ID string
}

// WithID adds the id to the get job ID params
func (o *GetJobIDParams) WithID(id string) *GetJobIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetJobIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
