package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// DeleteGroupsGroupNameJobsIDReader is a Reader for the DeleteGroupsGroupNameJobsID structure.
type DeleteGroupsGroupNameJobsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteGroupsGroupNameJobsIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteGroupsGroupNameJobsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewDeleteGroupsGroupNameJobsIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteGroupsGroupNameJobsIDOK creates a DeleteGroupsGroupNameJobsIDOK with default headers values
func NewDeleteGroupsGroupNameJobsIDOK() *DeleteGroupsGroupNameJobsIDOK {
	return &DeleteGroupsGroupNameJobsIDOK{}
}

/*DeleteGroupsGroupNameJobsIDOK handles this case with default header values.

Job successfully deleted. Deletion succeeds even on jobs that do not exist.
*/
type DeleteGroupsGroupNameJobsIDOK struct {
}

func (o *DeleteGroupsGroupNameJobsIDOK) Error() string {
	return fmt.Sprintf("[DELETE /groups/{group_name}/jobs/{id}][%d] deleteGroupsGroupNameJobsIdOK ", 200)
}

func (o *DeleteGroupsGroupNameJobsIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteGroupsGroupNameJobsIDConflict creates a DeleteGroupsGroupNameJobsIDConflict with default headers values
func NewDeleteGroupsGroupNameJobsIDConflict() *DeleteGroupsGroupNameJobsIDConflict {
	return &DeleteGroupsGroupNameJobsIDConflict{}
}

/*DeleteGroupsGroupNameJobsIDConflict handles this case with default header values.

Job is not in a valid state to delete.
*/
type DeleteGroupsGroupNameJobsIDConflict struct {
	Payload *models.IDStatus
}

func (o *DeleteGroupsGroupNameJobsIDConflict) Error() string {
	return fmt.Sprintf("[DELETE /groups/{group_name}/jobs/{id}][%d] deleteGroupsGroupNameJobsIdConflict  %+v", 409, o.Payload)
}

func (o *DeleteGroupsGroupNameJobsIDConflict) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IDStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
