package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteJobIDParams creates a new DeleteJobIDParams object
// with the default values initialized.
func NewDeleteJobIDParams() *DeleteJobIDParams {
	var ()
	return &DeleteJobIDParams{}
}

/*DeleteJobIDParams contains all the parameters to send to the API endpoint
for the delete job ID operation typically these are written to a http.Request
*/
type DeleteJobIDParams struct {

	/*ID
	  Job id

	*/
	ID string
}

// WithID adds the id to the delete job ID params
func (o *DeleteJobIDParams) WithID(id string) *DeleteJobIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteJobIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
