package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetJobIDLogParams creates a new GetJobIDLogParams object
// with the default values initialized.
func NewGetJobIDLogParams() *GetJobIDLogParams {
	var ()
	return &GetJobIDLogParams{}
}

/*GetJobIDLogParams contains all the parameters to send to the API endpoint
for the get job ID log operation typically these are written to a http.Request
*/
type GetJobIDLogParams struct {

	/*ID
	  Job id

	*/
	ID string
}

// WithID adds the id to the get job ID log params
func (o *GetJobIDLogParams) WithID(id string) *GetJobIDLogParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetJobIDLogParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
