package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// GetJobsConsumeReader is a Reader for the GetJobsConsume structure.
type GetJobsConsumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetJobsConsumeReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetJobsConsumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetJobsConsumeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetJobsConsumeOK creates a GetJobsConsumeOK with default headers values
func NewGetJobsConsumeOK() *GetJobsConsumeOK {
	return &GetJobsConsumeOK{}
}

/*GetJobsConsumeOK handles this case with default header values.

Job information
*/
type GetJobsConsumeOK struct {
	Payload *models.JobsWrapper
}

func (o *GetJobsConsumeOK) Error() string {
	return fmt.Sprintf("[GET /jobs/consume][%d] getJobsConsumeOK  %+v", 200, o.Payload)
}

func (o *GetJobsConsumeOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobsWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobsConsumeDefault creates a GetJobsConsumeDefault with default headers values
func NewGetJobsConsumeDefault(code int) *GetJobsConsumeDefault {
	return &GetJobsConsumeDefault{
		_statusCode: code,
	}
}

/*GetJobsConsumeDefault handles this case with default header values.

Unexpected error
*/
type GetJobsConsumeDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get jobs consume default response
func (o *GetJobsConsumeDefault) Code() int {
	return o._statusCode
}

func (o *GetJobsConsumeDefault) Error() string {
	return fmt.Sprintf("[GET /jobs/consume][%d] GetJobsConsume default  %+v", o._statusCode, o.Payload)
}

func (o *GetJobsConsumeDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
