package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetGroupsGroupNameJobsIDParams creates a new GetGroupsGroupNameJobsIDParams object
// with the default values initialized.
func NewGetGroupsGroupNameJobsIDParams() *GetGroupsGroupNameJobsIDParams {
	var ()
	return &GetGroupsGroupNameJobsIDParams{}
}

/*GetGroupsGroupNameJobsIDParams contains all the parameters to send to the API endpoint
for the get groups group name jobs ID operation typically these are written to a http.Request
*/
type GetGroupsGroupNameJobsIDParams struct {

	/*GroupName
	  Name of group for this set of jobs.

	*/
	GroupName string
	/*ID
	  Job id

	*/
	ID string
}

// WithGroupName adds the groupName to the get groups group name jobs ID params
func (o *GetGroupsGroupNameJobsIDParams) WithGroupName(groupName string) *GetGroupsGroupNameJobsIDParams {
	o.GroupName = groupName
	return o
}

// WithID adds the id to the get groups group name jobs ID params
func (o *GetGroupsGroupNameJobsIDParams) WithID(id string) *GetGroupsGroupNameJobsIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupsGroupNameJobsIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param group_name
	if err := r.SetPathParam("group_name", o.GroupName); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
