package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// GetGroupsGroupNameJobsReader is a Reader for the GetGroupsGroupNameJobs structure.
type GetGroupsGroupNameJobsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetGroupsGroupNameJobsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetGroupsGroupNameJobsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetGroupsGroupNameJobsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetGroupsGroupNameJobsOK creates a GetGroupsGroupNameJobsOK with default headers values
func NewGetGroupsGroupNameJobsOK() *GetGroupsGroupNameJobsOK {
	return &GetGroupsGroupNameJobsOK{}
}

/*GetGroupsGroupNameJobsOK handles this case with default header values.

Job information
*/
type GetGroupsGroupNameJobsOK struct {
	Payload *models.JobsWrapper
}

func (o *GetGroupsGroupNameJobsOK) Error() string {
	return fmt.Sprintf("[GET /groups/{group_name}/jobs][%d] getGroupsGroupNameJobsOK  %+v", 200, o.Payload)
}

func (o *GetGroupsGroupNameJobsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobsWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupsGroupNameJobsDefault creates a GetGroupsGroupNameJobsDefault with default headers values
func NewGetGroupsGroupNameJobsDefault(code int) *GetGroupsGroupNameJobsDefault {
	return &GetGroupsGroupNameJobsDefault{
		_statusCode: code,
	}
}

/*GetGroupsGroupNameJobsDefault handles this case with default header values.

Unexpected error
*/
type GetGroupsGroupNameJobsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get groups group name jobs default response
func (o *GetGroupsGroupNameJobsDefault) Code() int {
	return o._statusCode
}

func (o *GetGroupsGroupNameJobsDefault) Error() string {
	return fmt.Sprintf("[GET /groups/{group_name}/jobs][%d] GetGroupsGroupNameJobs default  %+v", o._statusCode, o.Payload)
}

func (o *GetGroupsGroupNameJobsDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
