package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// New creates a new jobs API client.
func New(transport client.Transport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for jobs API
*/
type Client struct {
	transport client.Transport
	formats   strfmt.Registry
}

/*
DeleteJobID deletes the job

Delete only succeeds if job status is one of `succeeded
| failed | cancelled`. Cancel a job if it is another state and needs to
be deleted.  All information about the job, including the log, is
irretrievably lost when this is invoked.

*/
func (a *Client) DeleteJobID(params *DeleteJobIDParams) (*DeleteJobIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteJobIDParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "DeleteJobID",
		Method:             "DELETE",
		PathPattern:        "/job/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteJobIDReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteJobIDOK), nil
}

/*
GetJobID gets job by id

Gets a job by id.
*/
func (a *Client) GetJobID(params *GetJobIDParams) (*GetJobIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetJobIDParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetJobID",
		Method:             "GET",
		PathPattern:        "/job/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetJobIDReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetJobIDOK), nil
}

/*
GetJobIDLog gets the log of a completed job

Retrieves the log from log storage.
*/
func (a *Client) GetJobIDLog(params *GetJobIDLogParams) (*GetJobIDLogOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetJobIDLogParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetJobIDLog",
		Method:             "GET",
		PathPattern:        "/job/{id}/log",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetJobIDLogReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetJobIDLogOK), nil
}

/*
GetJobs peeks at list of jobs

Get a list of active jobs. This endpoint can be used to observe the state of jobs in Titan. To run a job, use /jobs/consume. TODO: Needs pagination support.
*/
func (a *Client) GetJobs(params *GetJobsParams) (*GetJobsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetJobsParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetJobs",
		Method:             "GET",
		PathPattern:        "/jobs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetJobsReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetJobsOK), nil
}

/*
GetJobsConsume gets next job

Gets the next job in the queue, ready for processing. Titan may return <=n jobs. Consumers should start processing jobs in order. Each returned job is set to `status` "running" and `started_at` is set to the current time. No other consumer can retrieve this job.
*/
func (a *Client) GetJobsConsume(params *GetJobsConsumeParams) (*GetJobsConsumeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetJobsConsumeParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetJobsConsume",
		Method:             "GET",
		PathPattern:        "/jobs/consume",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetJobsConsumeReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetJobsConsumeOK), nil
}

/*
PatchJobID updates a job

Typically used to update status on error/completion. TODO: only allow 'status' field.
*/
func (a *Client) PatchJobID(params *PatchJobIDParams) (*PatchJobIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchJobIDParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "PatchJobID",
		Method:             "PATCH",
		PathPattern:        "/job/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PatchJobIDReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PatchJobIDOK), nil
}

/*
PostJobIDCancel cancels a job

Cancels a job in delayed, queued or running status. The worker may continue to run a running job. reason is set to `client_request`.
*/
func (a *Client) PostJobIDCancel(params *PostJobIDCancelParams) (*PostJobIDCancelOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostJobIDCancelParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "PostJobIDCancel",
		Method:             "POST",
		PathPattern:        "/job/{id}/cancel",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostJobIDCancelReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostJobIDCancelOK), nil
}

/*
PostJobIDFail marks job as failed

Job is marked as failed if it was in a valid state. Job's `completed_at` time is initialized.
*/
func (a *Client) PostJobIDFail(params *PostJobIDFailParams) (*PostJobIDFailOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostJobIDFailParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "PostJobIDFail",
		Method:             "POST",
		PathPattern:        "/job/{id}/fail",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostJobIDFailReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostJobIDFailOK), nil
}

/*
PostJobIDRetry retries a job

The /retry endpoint can be used to force a retry of jobs with status succeeded or cancelled. It can also be used to retry jobs that in the failed state, but whose max_retries field is 0. The retried job will continue to have max_retries = 0.
*/
func (a *Client) PostJobIDRetry(params *PostJobIDRetryParams) (*PostJobIDRetryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostJobIDRetryParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "PostJobIDRetry",
		Method:             "POST",
		PathPattern:        "/job/{id}/retry",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostJobIDRetryReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostJobIDRetryOK), nil
}

/*
PostJobIDSuccess marks job as succeeded

Job status is changed to succeeded if it was in a valid state before. Job's `completed_at` time is initialized.
*/
func (a *Client) PostJobIDSuccess(params *PostJobIDSuccessParams) (*PostJobIDSuccessOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostJobIDSuccessParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "PostJobIDSuccess",
		Method:             "POST",
		PathPattern:        "/job/{id}/success",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostJobIDSuccessReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostJobIDSuccessOK), nil
}

/*
PostJobIDTouch extends job timeout

Consumers can sometimes take a while to run the task after accepting it.  An example is when the runner does not have the docker image locally, it can spend a significant time downloading the image.
If the timeout is small, the job may never get to run, or run but not be accepted by Titan. Consumers can touch the job before it times out. Titan will reset the timeout, giving the consumer another timeout seconds to run the job.
Touch is only valid while the job is in a running state. If touch fails, the runner may stop running the job.
*/
func (a *Client) PostJobIDTouch(params *PostJobIDTouchParams) (*PostJobIDTouchOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostJobIDTouchParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "PostJobIDTouch",
		Method:             "POST",
		PathPattern:        "/job/{id}/touch",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostJobIDTouchReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostJobIDTouchOK), nil
}

/*
PostJobs enqueues job

Enqueues job(s). If any of the jobs is invalid, none of the jobs are enqueued.

*/
func (a *Client) PostJobs(params *PostJobsParams) (*PostJobsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostJobsParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "PostJobs",
		Method:             "POST",
		PathPattern:        "/jobs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostJobsReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostJobsCreated), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport client.Transport) {
	a.transport = transport
}
