package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// NewPatchGroupsGroupNameJobsIDParams creates a new PatchGroupsGroupNameJobsIDParams object
// with the default values initialized.
func NewPatchGroupsGroupNameJobsIDParams() *PatchGroupsGroupNameJobsIDParams {
	var ()
	return &PatchGroupsGroupNameJobsIDParams{}
}

/*PatchGroupsGroupNameJobsIDParams contains all the parameters to send to the API endpoint
for the patch groups group name jobs ID operation typically these are written to a http.Request
*/
type PatchGroupsGroupNameJobsIDParams struct {

	/*Body
	  Job data to post

	*/
	Body *models.JobWrapper
	/*GroupName
	  Name of group for this set of jobs.

	*/
	GroupName string
	/*ID
	  Job id

	*/
	ID string
}

// WithBody adds the body to the patch groups group name jobs ID params
func (o *PatchGroupsGroupNameJobsIDParams) WithBody(body *models.JobWrapper) *PatchGroupsGroupNameJobsIDParams {
	o.Body = body
	return o
}

// WithGroupName adds the groupName to the patch groups group name jobs ID params
func (o *PatchGroupsGroupNameJobsIDParams) WithGroupName(groupName string) *PatchGroupsGroupNameJobsIDParams {
	o.GroupName = groupName
	return o
}

// WithID adds the id to the patch groups group name jobs ID params
func (o *PatchGroupsGroupNameJobsIDParams) WithID(id string) *PatchGroupsGroupNameJobsIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PatchGroupsGroupNameJobsIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.JobWrapper)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param group_name
	if err := r.SetPathParam("group_name", o.GroupName); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
