package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// PatchGroupsGroupNameJobsIDReader is a Reader for the PatchGroupsGroupNameJobsID structure.
type PatchGroupsGroupNameJobsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PatchGroupsGroupNameJobsIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPatchGroupsGroupNameJobsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPatchGroupsGroupNameJobsIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPatchGroupsGroupNameJobsIDOK creates a PatchGroupsGroupNameJobsIDOK with default headers values
func NewPatchGroupsGroupNameJobsIDOK() *PatchGroupsGroupNameJobsIDOK {
	return &PatchGroupsGroupNameJobsIDOK{}
}

/*PatchGroupsGroupNameJobsIDOK handles this case with default header values.

Job updated.
*/
type PatchGroupsGroupNameJobsIDOK struct {
	Payload *models.JobWrapper
}

func (o *PatchGroupsGroupNameJobsIDOK) Error() string {
	return fmt.Sprintf("[PATCH /groups/{group_name}/jobs/{id}][%d] patchGroupsGroupNameJobsIdOK  %+v", 200, o.Payload)
}

func (o *PatchGroupsGroupNameJobsIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchGroupsGroupNameJobsIDDefault creates a PatchGroupsGroupNameJobsIDDefault with default headers values
func NewPatchGroupsGroupNameJobsIDDefault(code int) *PatchGroupsGroupNameJobsIDDefault {
	return &PatchGroupsGroupNameJobsIDDefault{
		_statusCode: code,
	}
}

/*PatchGroupsGroupNameJobsIDDefault handles this case with default header values.

Unexpected error
*/
type PatchGroupsGroupNameJobsIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the patch groups group name jobs ID default response
func (o *PatchGroupsGroupNameJobsIDDefault) Code() int {
	return o._statusCode
}

func (o *PatchGroupsGroupNameJobsIDDefault) Error() string {
	return fmt.Sprintf("[PATCH /groups/{group_name}/jobs/{id}][%d] PatchGroupsGroupNameJobsID default  %+v", o._statusCode, o.Payload)
}

func (o *PatchGroupsGroupNameJobsIDDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
