package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// PatchJobIDReader is a Reader for the PatchJobID structure.
type PatchJobIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PatchJobIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPatchJobIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPatchJobIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPatchJobIDOK creates a PatchJobIDOK with default headers values
func NewPatchJobIDOK() *PatchJobIDOK {
	return &PatchJobIDOK{}
}

/*PatchJobIDOK handles this case with default header values.

Job updated.
*/
type PatchJobIDOK struct {
	Payload *models.JobWrapper
}

func (o *PatchJobIDOK) Error() string {
	return fmt.Sprintf("[PATCH /job/{id}][%d] patchJobIdOK  %+v", 200, o.Payload)
}

func (o *PatchJobIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchJobIDDefault creates a PatchJobIDDefault with default headers values
func NewPatchJobIDDefault(code int) *PatchJobIDDefault {
	return &PatchJobIDDefault{
		_statusCode: code,
	}
}

/*PatchJobIDDefault handles this case with default header values.

Unexpected error
*/
type PatchJobIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the patch job ID default response
func (o *PatchJobIDDefault) Code() int {
	return o._statusCode
}

func (o *PatchJobIDDefault) Error() string {
	return fmt.Sprintf("[PATCH /job/{id}][%d] PatchJobID default  %+v", o._statusCode, o.Payload)
}

func (o *PatchJobIDDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
