package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewPostJobIDCancelParams creates a new PostJobIDCancelParams object
// with the default values initialized.
func NewPostJobIDCancelParams() *PostJobIDCancelParams {
	var ()
	return &PostJobIDCancelParams{}
}

/*PostJobIDCancelParams contains all the parameters to send to the API endpoint
for the post job ID cancel operation typically these are written to a http.Request
*/
type PostJobIDCancelParams struct {

	/*Details
	  Human-readable detailed message explaining cancellation reason.

	*/
	Details *string
	/*ID
	  Job id

	*/
	ID string
}

// WithDetails adds the details to the post job ID cancel params
func (o *PostJobIDCancelParams) WithDetails(details *string) *PostJobIDCancelParams {
	o.Details = details
	return o
}

// WithID adds the id to the post job ID cancel params
func (o *PostJobIDCancelParams) WithID(id string) *PostJobIDCancelParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostJobIDCancelParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Details); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
