package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// PostGroupsGroupNameJobsReader is a Reader for the PostGroupsGroupNameJobs structure.
type PostGroupsGroupNameJobsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostGroupsGroupNameJobsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostGroupsGroupNameJobsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostGroupsGroupNameJobsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostGroupsGroupNameJobsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostGroupsGroupNameJobsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostGroupsGroupNameJobsCreated creates a PostGroupsGroupNameJobsCreated with default headers values
func NewPostGroupsGroupNameJobsCreated() *PostGroupsGroupNameJobsCreated {
	return &PostGroupsGroupNameJobsCreated{}
}

/*PostGroupsGroupNameJobsCreated handles this case with default header values.

Job created
*/
type PostGroupsGroupNameJobsCreated struct {
	Payload *models.JobsWrapper
}

func (o *PostGroupsGroupNameJobsCreated) Error() string {
	return fmt.Sprintf("[POST /groups/{group_name}/jobs][%d] postGroupsGroupNameJobsCreated  %+v", 201, o.Payload)
}

func (o *PostGroupsGroupNameJobsCreated) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobsWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGroupsGroupNameJobsBadRequest creates a PostGroupsGroupNameJobsBadRequest with default headers values
func NewPostGroupsGroupNameJobsBadRequest() *PostGroupsGroupNameJobsBadRequest {
	return &PostGroupsGroupNameJobsBadRequest{}
}

/*PostGroupsGroupNameJobsBadRequest handles this case with default header values.

One or more of the jobs were invalid due to parameters being missing or invalid.
*/
type PostGroupsGroupNameJobsBadRequest struct {
	Payload *models.Error
}

func (o *PostGroupsGroupNameJobsBadRequest) Error() string {
	return fmt.Sprintf("[POST /groups/{group_name}/jobs][%d] postGroupsGroupNameJobsBadRequest  %+v", 400, o.Payload)
}

func (o *PostGroupsGroupNameJobsBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGroupsGroupNameJobsInternalServerError creates a PostGroupsGroupNameJobsInternalServerError with default headers values
func NewPostGroupsGroupNameJobsInternalServerError() *PostGroupsGroupNameJobsInternalServerError {
	return &PostGroupsGroupNameJobsInternalServerError{}
}

/*PostGroupsGroupNameJobsInternalServerError handles this case with default header values.

Titan could not accept jobs due to internal error.
*/
type PostGroupsGroupNameJobsInternalServerError struct {
	Payload *models.Error
}

func (o *PostGroupsGroupNameJobsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /groups/{group_name}/jobs][%d] postGroupsGroupNameJobsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostGroupsGroupNameJobsInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGroupsGroupNameJobsDefault creates a PostGroupsGroupNameJobsDefault with default headers values
func NewPostGroupsGroupNameJobsDefault(code int) *PostGroupsGroupNameJobsDefault {
	return &PostGroupsGroupNameJobsDefault{
		_statusCode: code,
	}
}

/*PostGroupsGroupNameJobsDefault handles this case with default header values.

Unexpected error
*/
type PostGroupsGroupNameJobsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post groups group name jobs default response
func (o *PostGroupsGroupNameJobsDefault) Code() int {
	return o._statusCode
}

func (o *PostGroupsGroupNameJobsDefault) Error() string {
	return fmt.Sprintf("[POST /groups/{group_name}/jobs][%d] PostGroupsGroupNameJobs default  %+v", o._statusCode, o.Payload)
}

func (o *PostGroupsGroupNameJobsDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
