package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// NewPostJobsParams creates a new PostJobsParams object
// with the default values initialized.
func NewPostJobsParams() *PostJobsParams {
	var ()
	return &PostJobsParams{}
}

/*PostJobsParams contains all the parameters to send to the API endpoint
for the post jobs operation typically these are written to a http.Request
*/
type PostJobsParams struct {

	/*Body
	  Array of jobs to post.

	*/
	Body *models.NewJobsWrapper
}

// WithBody adds the body to the post jobs params
func (o *PostJobsParams) WithBody(body *models.NewJobsWrapper) *PostJobsParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostJobsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.NewJobsWrapper)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
