package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// PostGroupsGroupNameJobsIDCancelReader is a Reader for the PostGroupsGroupNameJobsIDCancel structure.
type PostGroupsGroupNameJobsIDCancelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostGroupsGroupNameJobsIDCancelReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostGroupsGroupNameJobsIDCancelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPostGroupsGroupNameJobsIDCancelConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostGroupsGroupNameJobsIDCancelDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostGroupsGroupNameJobsIDCancelOK creates a PostGroupsGroupNameJobsIDCancelOK with default headers values
func NewPostGroupsGroupNameJobsIDCancelOK() *PostGroupsGroupNameJobsIDCancelOK {
	return &PostGroupsGroupNameJobsIDCancelOK{}
}

/*PostGroupsGroupNameJobsIDCancelOK handles this case with default header values.

Job cancelled.
*/
type PostGroupsGroupNameJobsIDCancelOK struct {
	Payload *models.JobWrapper
}

func (o *PostGroupsGroupNameJobsIDCancelOK) Error() string {
	return fmt.Sprintf("[POST /groups/{group_name}/jobs/{id}/cancel][%d] postGroupsGroupNameJobsIdCancelOK  %+v", 200, o.Payload)
}

func (o *PostGroupsGroupNameJobsIDCancelOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGroupsGroupNameJobsIDCancelConflict creates a PostGroupsGroupNameJobsIDCancelConflict with default headers values
func NewPostGroupsGroupNameJobsIDCancelConflict() *PostGroupsGroupNameJobsIDCancelConflict {
	return &PostGroupsGroupNameJobsIDCancelConflict{}
}

/*PostGroupsGroupNameJobsIDCancelConflict handles this case with default header values.

Could not cancel job because it already succeeded or failed.
*/
type PostGroupsGroupNameJobsIDCancelConflict struct {
	Payload *models.Error
}

func (o *PostGroupsGroupNameJobsIDCancelConflict) Error() string {
	return fmt.Sprintf("[POST /groups/{group_name}/jobs/{id}/cancel][%d] postGroupsGroupNameJobsIdCancelConflict  %+v", 409, o.Payload)
}

func (o *PostGroupsGroupNameJobsIDCancelConflict) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGroupsGroupNameJobsIDCancelDefault creates a PostGroupsGroupNameJobsIDCancelDefault with default headers values
func NewPostGroupsGroupNameJobsIDCancelDefault(code int) *PostGroupsGroupNameJobsIDCancelDefault {
	return &PostGroupsGroupNameJobsIDCancelDefault{
		_statusCode: code,
	}
}

/*PostGroupsGroupNameJobsIDCancelDefault handles this case with default header values.

Unexpected error
*/
type PostGroupsGroupNameJobsIDCancelDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post groups group name jobs ID cancel default response
func (o *PostGroupsGroupNameJobsIDCancelDefault) Code() int {
	return o._statusCode
}

func (o *PostGroupsGroupNameJobsIDCancelDefault) Error() string {
	return fmt.Sprintf("[POST /groups/{group_name}/jobs/{id}/cancel][%d] PostGroupsGroupNameJobsIDCancel default  %+v", o._statusCode, o.Payload)
}

func (o *PostGroupsGroupNameJobsIDCancelDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
