package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewPostJobIDTouchParams creates a new PostJobIDTouchParams object
// with the default values initialized.
func NewPostJobIDTouchParams() *PostJobIDTouchParams {
	var ()
	return &PostJobIDTouchParams{}
}

/*PostJobIDTouchParams contains all the parameters to send to the API endpoint
for the post job ID touch operation typically these are written to a http.Request
*/
type PostJobIDTouchParams struct {

	/*ID
	  Job id

	*/
	ID string
}

// WithID adds the id to the post job ID touch params
func (o *PostJobIDTouchParams) WithID(id string) *PostJobIDTouchParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostJobIDTouchParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
