package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// PostJobsReader is a Reader for the PostJobs structure.
type PostJobsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostJobsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostJobsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostJobsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostJobsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostJobsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostJobsCreated creates a PostJobsCreated with default headers values
func NewPostJobsCreated() *PostJobsCreated {
	return &PostJobsCreated{}
}

/*PostJobsCreated handles this case with default header values.

Job created
*/
type PostJobsCreated struct {
	Payload *models.JobsWrapper
}

func (o *PostJobsCreated) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] postJobsCreated  %+v", 201, o.Payload)
}

func (o *PostJobsCreated) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobsWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostJobsBadRequest creates a PostJobsBadRequest with default headers values
func NewPostJobsBadRequest() *PostJobsBadRequest {
	return &PostJobsBadRequest{}
}

/*PostJobsBadRequest handles this case with default header values.

One or more of the jobs were invalid due to parameters being missing or invalid.
*/
type PostJobsBadRequest struct {
	Payload *models.Error
}

func (o *PostJobsBadRequest) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] postJobsBadRequest  %+v", 400, o.Payload)
}

func (o *PostJobsBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostJobsInternalServerError creates a PostJobsInternalServerError with default headers values
func NewPostJobsInternalServerError() *PostJobsInternalServerError {
	return &PostJobsInternalServerError{}
}

/*PostJobsInternalServerError handles this case with default header values.

Titan could not accept jobs due to internal error.
*/
type PostJobsInternalServerError struct {
	Payload *models.Error
}

func (o *PostJobsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] postJobsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostJobsInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostJobsDefault creates a PostJobsDefault with default headers values
func NewPostJobsDefault(code int) *PostJobsDefault {
	return &PostJobsDefault{
		_statusCode: code,
	}
}

/*PostJobsDefault handles this case with default header values.

Unexpected error
*/
type PostJobsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post jobs default response
func (o *PostJobsDefault) Code() int {
	return o._statusCode
}

func (o *PostJobsDefault) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] PostJobs default  %+v", o._statusCode, o.Payload)
}

func (o *PostJobsDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
