package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"os"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewPostGroupsGroupNameJobsIDLogParams creates a new PostGroupsGroupNameJobsIDLogParams object
// with the default values initialized.
func NewPostGroupsGroupNameJobsIDLogParams() *PostGroupsGroupNameJobsIDLogParams {
	var ()
	return &PostGroupsGroupNameJobsIDLogParams{}
}

/*PostGroupsGroupNameJobsIDLogParams contains all the parameters to send to the API endpoint
for the post groups group name jobs ID log operation typically these are written to a http.Request
*/
type PostGroupsGroupNameJobsIDLogParams struct {

	/*GroupName
	  Name of group for this set of jobs.

	*/
	GroupName string
	/*ID
	  Job id

	*/
	ID string
	/*Log
	  Output log for the job. Content-Type must be "text/plain; charset=utf-8".

	*/
	Log os.File
}

// WithGroupName adds the groupName to the post groups group name jobs ID log params
func (o *PostGroupsGroupNameJobsIDLogParams) WithGroupName(groupName string) *PostGroupsGroupNameJobsIDLogParams {
	o.GroupName = groupName
	return o
}

// WithID adds the id to the post groups group name jobs ID log params
func (o *PostGroupsGroupNameJobsIDLogParams) WithID(id string) *PostGroupsGroupNameJobsIDLogParams {
	o.ID = id
	return o
}

// WithLog adds the log to the post groups group name jobs ID log params
func (o *PostGroupsGroupNameJobsIDLogParams) WithLog(log os.File) *PostGroupsGroupNameJobsIDLogParams {
	o.Log = log
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostGroupsGroupNameJobsIDLogParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param group_name
	if err := r.SetPathParam("group_name", o.GroupName); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// form file param log
	if err := r.SetFileParam("log", &o.Log); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
