package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetGroupsNameParams creates a new GetGroupsNameParams object
// with the default values initialized.
func NewGetGroupsNameParams() *GetGroupsNameParams {
	var ()
	return &GetGroupsNameParams{}
}

/*GetGroupsNameParams contains all the parameters to send to the API endpoint
for the get groups name operation typically these are written to a http.Request
*/
type GetGroupsNameParams struct {

	/*Name
	  name of the group.

	*/
	Name string
}

// WithName adds the name to the get groups name params
func (o *GetGroupsNameParams) WithName(name string) *GetGroupsNameParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupsNameParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
