package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// GetGroupsReader is a Reader for the GetGroups structure.
type GetGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetGroupsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetGroupsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetGroupsOK creates a GetGroupsOK with default headers values
func NewGetGroupsOK() *GetGroupsOK {
	return &GetGroupsOK{}
}

/*GetGroupsOK handles this case with default header values.

List of groups.
*/
type GetGroupsOK struct {
	Payload *models.GroupsWrapper
}

func (o *GetGroupsOK) Error() string {
	return fmt.Sprintf("[GET /groups][%d] getGroupsOK  %+v", 200, o.Payload)
}

func (o *GetGroupsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupsWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupsDefault creates a GetGroupsDefault with default headers values
func NewGetGroupsDefault(code int) *GetGroupsDefault {
	return &GetGroupsDefault{
		_statusCode: code,
	}
}

/*GetGroupsDefault handles this case with default header values.

Unexpected error
*/
type GetGroupsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get groups default response
func (o *GetGroupsDefault) Code() int {
	return o._statusCode
}

func (o *GetGroupsDefault) Error() string {
	return fmt.Sprintf("[GET /groups][%d] GetGroups default  %+v", o._statusCode, o.Payload)
}

func (o *GetGroupsDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
