package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*ErrorBody error body

swagger:model ErrorBody
*/
type ErrorBody struct {

	/* fields

	Read Only: true
	*/
	Fields string `json:"fields,omitempty"`

	/* message

	Required: true
	Read Only: true
	*/
	Message string `json:"message"`
}

// Validate validates this error body
func (m *ErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}
