package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Group group

swagger:model Group
*/
type Group struct {

	/* Time when image first used/created.

	Read Only: true
	*/
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	/* Name of this group. Must be different than the image name. Can ony contain alphanumeric, -, and _.

	Required: true
	Read Only: true
	*/
	Name string `json:"name"`
}

// Validate validates this group
func (m *Group) Validate(formats strfmt.Registry) error {
	return nil
}
