package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*ImagesWrapper images wrapper

swagger:model ImagesWrapper
*/
type ImagesWrapper struct {

	/* images

	Required: true
	*/
	Images []*Image `json:"images"`
}

// Validate validates this images wrapper
func (m *ImagesWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImages(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImagesWrapper) validateImages(formats strfmt.Registry) error {

	if err := validate.Required("images", "body", m.Images); err != nil {
		return err
	}

	for i := 0; i < len(m.Images); i++ {

		if err := m.Images[i].Validate(formats); err != nil {
			return err
		}

	}

	return nil
}
