package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*Image image

swagger:model Image
*/
type Image struct {

	/* Time when image first used/created.
	 */
	CreatedAt *strfmt.DateTime `json:"created_at,omitempty"`

	/* Docker image to use for job, including the tag.

	Required: true
	*/
	Image string `json:"image"`

	/* Name of this image/package/code. Can and should be different than the image name (shoudn't include tag). TODO: Should we strip tag automatically if only image is passed in?
	 */
	Name *string `json:"name,omitempty"`
}

// Validate validates this image
func (m *Image) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Image) validateImage(formats strfmt.Registry) error {

	if err := validate.RequiredString("image", "body", string(m.Image)); err != nil {
		return err
	}

	return nil
}
