package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
)

/*ImageWrapper image wrapper

swagger:model ImageWrapper
*/
type ImageWrapper struct {

	/* image

	Required: true
	*/
	Image *Image `json:"image"`
}

// Validate validates this image wrapper
func (m *ImageWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImageWrapper) validateImage(formats strfmt.Registry) error {

	if m.Image != nil {

		if err := m.Image.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
