package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
)

/*JobWrapper job wrapper

swagger:model JobWrapper
*/
type JobWrapper struct {

	/* job

	Required: true
	*/
	Job *Job `json:"job"`
}

// Validate validates this job wrapper
func (m *JobWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJob(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobWrapper) validateJob(formats strfmt.Registry) error {

	if m.Job != nil {

		if err := m.Job.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
