package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*JobsWrapper jobs wrapper

swagger:model JobsWrapper
*/
type JobsWrapper struct {

	/* error
	 */
	Error *ErrorBody `json:"error,omitempty"`

	/* jobs

	Required: true
	*/
	Jobs []*Job `json:"jobs"`
}

// Validate validates this jobs wrapper
func (m *JobsWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJobs(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobsWrapper) validateJobs(formats strfmt.Registry) error {

	if err := validate.Required("jobs", "body", m.Jobs); err != nil {
		return err
	}

	for i := 0; i < len(m.Jobs); i++ {

		if m.Jobs[i] != nil {

			if err := m.Jobs[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
