package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Start start

swagger:model Start
*/
type Start struct {

	/* Time when job started execution. Always in UTC.
	 */
	StartedAt strfmt.DateTime `json:"started_at,omitempty"`
}

// Validate validates this start
func (m *Start) Validate(formats strfmt.Registry) error {
	return nil
}
