package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetImageIDParams creates a new GetImageIDParams object
// with the default values initialized.
func NewGetImageIDParams() *GetImageIDParams {
	var ()
	return &GetImageIDParams{}
}

/*GetImageIDParams contains all the parameters to send to the API endpoint
for the get image ID operation typically these are written to a http.Request
*/
type GetImageIDParams struct {

	/*ID
	  ID of the image.

	*/
	ID string
}

// WithID adds the id to the get image ID params
func (o *GetImageIDParams) WithID(id string) *GetImageIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
