package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/models"
)

// GetImagesReader is a Reader for the GetImages structure.
type GetImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetImagesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetImagesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetImagesOK creates a GetImagesOK with default headers values
func NewGetImagesOK() *GetImagesOK {
	return &GetImagesOK{}
}

/*GetImagesOK handles this case with default header values.

List of images.
*/
type GetImagesOK struct {
	Payload *models.ImagesWrapper
}

func (o *GetImagesOK) Error() string {
	return fmt.Sprintf("[GET /images][%d] getImagesOK  %+v", 200, o.Payload)
}

func (o *GetImagesOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImagesWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImagesDefault creates a GetImagesDefault with default headers values
func NewGetImagesDefault(code int) *GetImagesDefault {
	return &GetImagesDefault{
		_statusCode: code,
	}
}

/*GetImagesDefault handles this case with default header values.

Unexpected error
*/
type GetImagesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get images default response
func (o *GetImagesDefault) Code() int {
	return o._statusCode
}

func (o *GetImagesDefault) Error() string {
	return fmt.Sprintf("[GET /images][%d] GetImages default  %+v", o._statusCode, o.Payload)
}

func (o *GetImagesDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
