package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// New creates a new images API client.
func New(transport client.Transport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for images API
*/
type Client struct {
	transport client.Transport
	formats   strfmt.Registry
}

/*
GetImageID gets information for image id

This gives more details about on image, such as the image name and other statistics.
*/
func (a *Client) GetImageID(params *GetImageIDParams) (*GetImageIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetImageIDParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetImageID",
		Method:             "GET",
		PathPattern:        "/image/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetImageIDReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetImageIDOK), nil
}

/*
GetImages gets all image names

TODO: Using images for lack of a better term. See https://github.com/iron-io/titan/issues/43 for discussion.
*/
func (a *Client) GetImages(params *GetImagesParams) (*GetImagesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetImagesParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetImages",
		Method:             "GET",
		PathPattern:        "/images",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetImagesReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetImagesOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport client.Transport) {
	a.transport = transport
}
