package titan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	httptransport "github.com/go-swagger/go-swagger/httpkit/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/iron-io/titan/runner/client/titan/groups"
	"github.com/iron-io/titan/runner/client/titan/jobs"
	"github.com/iron-io/titan/runner/client/titan/runner"
)

// Default titan HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new titan HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Titan {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost:8080", "/v1", []string{"http", "https"})
	return New(transport, formats)
}

// New creates a new titan client
func New(transport client.Transport, formats strfmt.Registry) *Titan {
	cli := new(Titan)
	cli.Transport = transport

	cli.Groups = groups.New(transport, formats)

	cli.Jobs = jobs.New(transport, formats)

	cli.Runner = runner.New(transport, formats)

	return cli
}

// Titan is a client for titan
type Titan struct {
	Groups *groups.Client

	Jobs *jobs.Client

	Runner *runner.Client

	Transport client.Transport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Titan) SetTransport(transport client.Transport) {
	c.Transport = transport

	c.Groups.SetTransport(transport)

	c.Jobs.SetTransport(transport)

	c.Runner.SetTransport(transport)

}
